# Generated by Django 5.0.14 on 2026-01-10 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='receiver_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='contact_info',
            new_name='resolved_contact',
        ),
        migrations.RemoveField(
            model_name='item',
            name='receiver_contact',
        ),
        migrations.AddField(
            model_name='item',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='item',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='resolved_contact_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Telefone')], max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='resolved_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('lost', 'Perdido'), ('found', 'Encontrado')], default='lost', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('resolved', 'Resolvido')], default='active', max_length=10),
        ),
    ]
