# Generated by Django 5.0.14 on 2026-01-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_receiver_name_item_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
